export const START_LOADING = 'START_LOADING';
export const SUCCESS_LOADING = 'SUCCESS_LOADING';
export const ERROR_LOADING = 'ERROR_LOADING';
export const SET_RATING_FILTER = 'SET_RATING_FILTER';
export const SET_COMMENT_FILTER = 'SET_COMMENT_FILTER';
export const SET_PAGE = 'SET_PAGE';
